import Head from "next/head";
import { Navbar } from "@/components/Navbar/Navbar";
import { Inter } from "next/font/google";
import styles from "./MainLayout.module.css";

interface Props {
  children: JSX.Element | JSX.Element[];
}

const inter = Inter({ subsets: ["latin"] });

export const MainLayout = ({ children }: Props) => {
  return (
    <>
      <Navbar />

      <div className={styles.container}>
        <Head>
          <title>About</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={`${styles.main} ${inter.className}`}>{children}</main>
      </div>
    </>
  );
};
